FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

RUN dotnet tool install -g upgrade-assistant
ENV PATH=$PATH:/root/.dotnet/tools

ENV DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT=1

WORKDIR /src

COPY Framework/Net/WebChemistry.Framework.Core/ ./Framework/Net/WebChemistry.Framework.Core/
COPY AppsAndServices/Queries/WebChemistry.Queries.Core/ ./AppsAndServices/Queries/WebChemistry.Queries.Core/
COPY AppsAndServices/Tunnels/WebChemistry.Tunnels.Core/ ./AppsAndServices/Tunnels/WebChemistry.Tunnels.Core/
COPY AppsAndServices/Tunnels/WebChemistry.Tunnels.Server/ ./AppsAndServices/Tunnels/WebChemistry.Tunnels.Server/

RUN cmd='upgrade-assistant upgrade --non-interactive -f net10.0 -o Inplace' \
&& $cmd ./Framework/Net/WebChemistry.Framework.Core/WebChemistry.Framework.Core.csproj \
&& $cmd ./AppsAndServices/Queries/WebChemistry.Queries.Core/WebChemistry.Queries.Core.csproj \
&& $cmd ./AppsAndServices/Tunnels/WebChemistry.Tunnels.Core/WebChemistry.Tunnels.Core.csproj \
&& $cmd ./AppsAndServices/Tunnels/WebChemistry.Tunnels.Server/WebChemistry.Tunnels.Server.csproj

RUN dotnet publish AppsAndServices/Tunnels/WebChemistry.Tunnels.Server/WebChemistry.Tunnels.Server.csproj \
    -c Release \
    -o /app/publish \
    /p:GenerateAssemblyInfo=false


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

RUN chown -R app:app /app

USER app

ENTRYPOINT ["/app/mole2"]
